### ISSUE TITLE
Agent `Boot-Class-Path` manifest attributes requires specific file name

### ISSUE THREAD

**Issue by andrioli** [saeg/ba-dua#28]
The Agent `Boot-Class-Path` manifest attribute is a constant and the agent will not work if file name is different of the expected value `ba-dua-agent-rt-${ba-dua.version}-all.jar`.

If the file name is different we got the following error:

```
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : target/dependency/ba-dua-agent-rt-0.6.0-all.jar
```

See:

https://github.com/saeg/jaguar2/pull/10#discussion_r753702490
saeg/jaguar2@434bcdd

**Comment by andrioli** [comment]
It is working now: see: https://github.com/saeg/jaguar2/pull/18

Just for the sake of keep documentation fine, the correct error is: 

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: Lbr/usp/each/saeg/badua/agent/rt/internal_d2401f0/core/runtime/RuntimeData;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at br.usp.each.saeg.badua.agent.rt.internal_d2401f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:65)
	at br.usp.each.saeg.badua.agent.rt.internal_d2401f0.PreMain.premain(PreMain.java:25)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

and not the `Error opening zip file or JAR manifest missing` one.

see commit https://github.com/saeg/jaguar2/pull/18/commits/935759ba3dadae2bbd7cb63626ebf17e56e06115 for more details
